name: Backend CI

on:
  pull_request:
    paths:
    - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Dotenv Action
        uses: falti/dotenv-action@v0.2.8
        with:
          envkey_PORT: ${{ steps.dotenv.outputs.port }}
          envkey_MYSQL_HOST: ${{ steps.dotenv.outputs.port.mysql_host }}
          envkey_MYSQL_USER: ${{ steps.dotenv.outputs.port.mysql_user }}
          envkey_MYSQL_PASSWORD: ${{ steps.dotenv.outputs.port.mysql_password }}
          envkey_MYSQL_DATABASE: ${{ steps.dotenv.outputs.port.mysql_database }}
          envkey_ACCESS_TOKEN_SECRET: ${{ steps.dotenv.outputs.port.access_token_secret }}
          file_name: .env
          fail_on_empty: true
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
      working-directory: ./backend
    - name: Run Tests
      run: npm run test:ci -- --passWithNoTests
      working-directory: ./backend
    - name: Run Linter
      run: npm run lint
      working-directory: ./backend
