name: Backend CI

on:
  pull_request:
    paths:
    - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{ secrets.PORT }}
          envkey_MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          envkey_MYSQL_USER: ${{ secrets.MYSQL_USER }}
          envkey_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          envkey_MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          file_name: .env
          fail_on_empty: true
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
      working-directory: ./backend
    - name: Run Tests
      run: npm run test:ci -- --passWithNoTests
      working-directory: ./backend
    - name: Run Linter
      run: npm run lint
      working-directory: ./backend
