name: Backend CI

on:
  pull_request:
    paths:
    - 'backend/**'
env:
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
      working-directory: ./backend
    - name: Run Tests
      run: npm test -- --passWithNoTests
      working-directory: ./backend
    - name: Run Linter
      run: npm lint
      working-directory: ./backend
