name: Backend CI

on:
  pull_request:
    paths:
    - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: todo
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - run: mysql -h 127.0.0.1 --port 3306 -u root -ppassword'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
      working-directory: ./backend
    - name: Run Tests
      run: npm run test:ci -- --passWithNoTests
      working-directory: ./backend
    - name: Run Linter
      run: npm run lint
      working-directory: ./backend
